openapi: "3.0.3"

info:
  title: ShanyLedger App
  description: これはShanyLedgerのAPIサーバーの仕様です。
  termsOfService: https://shany-ledger.com/terms
  contact:
    name: API Support
    url: https://shany-ledger.com/support
    email: support@shany-ledger.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.0

servers:
  - url: http://localhost/v1
    description: 開発環境
  - url: https://api.shany-ledger.com/v1
    description: 本番環境

tags:
  - name: auth
    description: ユーザーの認証・認可に関するAPIグループです。

paths:
  /signup:
    $ref: "./auth/signup/paths.yml"
