openapi: "3.0.3"

info:
  title: ShanyLedger App
  description: これはShanyLedgerのAPIサーバーの仕様です。
  termsOfService: https://shany-ledger.com/terms
  contact:
    name: API Support
    url: https://shany-ledger.com/support
    email: support@shany-ledger.com
  license:
    name: CC(Creative Commons)
    url: https://creativecommons.org/licenses/
  version: 0.0.21

servers:
- url: http://localhost/v1
  description: 開発環境
- url: https://api.shany-ledger.com/v1
  description: 本番環境

tags:
- name: auth
  description: ユーザーの認証・認可に関するAPIグループです。
- name: workspace
  description: ワークスペースに関するAPIグループです。

paths:
  /sign-up:
    $ref: "./auth/signup/paths.yml"
  /sign-in:
    $ref: "./auth/signin/paths.yml"
  /workspaces:
    $ref: "./workspace/paths.yml#/Workspaces"
  /workspaces/[workspaceId]:
    $ref: "./workspace/paths.yml#/Workspace"
  /workspaces/[workspaceId]/security:
    $ref: "./workspace/security/paths.yml"
  /workspaces/[workspaceId]/members:
    $ref: "./workspace/member/paths.yml#/Members"
  /workspaces/[workspaceId]/members/[memberId]:
    $ref: "./workspace/member/paths.yml#/Member"
  /workspaces/[workspaceId]/members/[memberId]/security:
    $ref: "./workspace/member/security/paths.yml"
  /workspaces/[workspaceId]/invitations:
    $ref: "./workspace/invitation/paths.yml#/Invitations"
  /workspaces/[workspaceId]/invitations/[workspaceInvitationId]:
    $ref: "./workspace/invitation/paths.yml#/Invitation"

components:
  schemas:
    BadRequestError:
      $ref: "./error/400_bad_request/schemas.yml#/BadRequestError"
    UnauthorizedError:
      $ref: "./error/401_unauthorized/schemas.yml#/UnauthorizedError"
    ForbiddenError:
      $ref: "./error/403_forbidden/schemas.yml#/ForbiddenError"
    NotFoundError:
      $ref: "./error/404_not_found/schemas.yml#/NotFoundError"
    RequestTimeoutError:
      $ref: "./error/408_request_timeout/schemas.yml#/RequestTimeoutError"
    ConflictError:
      $ref: "./error/409_conflict/schemas.yml#/ConflictError"
    GoneError:
      $ref: "./error/410_gone/schemas.yml#/GoneError"
    TooManyRequestsError:
      $ref: "./error/429_too_many_requests/schemas.yml#/TooManyRequestsError"
    InternalServerError:
      $ref: "./error/500_internal_server_error/schemas.yml#/InternalServerError"
    BadGatewayError:
      $ref: "./error/502_bad_gateway/schemas.yml#/BadGatewayError"
    ServiceUnavailableError:
      $ref: "./error/503_service_unavailable/schemas.yml#/ServiceUnavailableError"
  headers:
    X-RateLimit-Limit:
      description: 15分あたりのリクエスト制限です。
      schema:
        type: integer
    X-RateLimit-Remaining:
      description: タイムウィンドウに残っているリクエストの数です。
      schema:
        type: integer
    X-RateLimit-Reset:
      description: 現在のレートリミットウィンドウがリセットされるUTC日時です。
      schema:
        type: string
        format: date-time
    Retry-After:
      description: 現在のレートリミットウィンドウがリセットされるまでの秒数です。
      schema:
        type: integer
    Location:
      description: リダイレクト先のURLを示します。
      schema:
        type: string
        format: uri
