WorkspaceUrl:
  name: workspaceUrl
  in: path
  description: ワークスペースのIDです。
  required: true
  schema:
    $ref: "./schemas.yml#/WorkspaceUrl"

WorkspaceFreeWord:
  name: free_word
  in: query
  description: ワークスペースのフリーワード検索です。
  required: false
  schema:
    type: string
    max: 100
